### ISSUE TITLE
añadir listado de ultimas fotos duras publicadas

### ISSUE THREAD

**Issue by roxandtol** [roxandtol/durobot#1]
para evitar duplicados, despues se añadiría una linea en el config para poner las fotos que no se pueden subir

**Comment by TheRepSter** [comment]
Si lo que se quiere evitar son duplicados, no sería mejor un hash o detector de similitud de imagen? En el segundo caso se puede hacer que para evitar falsos positivos enseñar la imagen que se piensa igual.

**Comment by roxandtol** [comment]
Es mas bien para que cuando haces el comando, y te da foto 1, si lo haces de nuevo, no te de la foto 1, sino otra
